# Generated by Django 5.2.8 on 2025-11-11 22:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave de Configuração')),
                ('valor', models.TextField(verbose_name='Valor da Configuração')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_grupo_indice', models.CharField(help_text='Nome único para o grupo de índice.', max_length=150, unique=True, verbose_name='Nome do Grupo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Grupo de Índice',
                'verbose_name_plural': 'Grupos de Índices',
                'ordering': ['nome_grupo_indice'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_relatorio', models.CharField(max_length=255, verbose_name='Nome do Relatório')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Relatório')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_tipo_acao', models.CharField(max_length=255, unique=True, verbose_name='Nome da Ação')),
                ('motivo_tipo_acao', models.TextField(verbose_name='Motivo da Ação')),
                ('mensagem_padrao_avaliacao', models.TextField(blank=True, null=True, verbose_name='Mensagem Padrão para Avaliação')),
                ('mensagem_padrao_conclusao', models.TextField(blank=True, null=True, verbose_name='Mensagem Padrão para Conclusão')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_tipo_indice', models.CharField(max_length=255, null=True, verbose_name='nome tipo indice')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('indice_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.grupoindice', verbose_name='Grupo do Índice')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cpf', encrypted_model_fields.fields.EncryptedCharField(unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('perfil', models.CharField(choices=[('CHEFE', 'Chefe'), ('FUNCIONARIO', 'Funcionário')], default='FUNCIONARIO', max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Acesso')),
                ('ip_acesso', models.GenericIPAddressField(verbose_name='IP de Acesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAlteracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_hora_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Alteração')),
                ('tipo_objeto', models.CharField(max_length=100, verbose_name='Tipo do Objeto')),
                ('id_objeto', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('descricao_alteracao', models.TextField(verbose_name='Descrição da Alteração')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_auditoria', models.CharField(max_length=255, verbose_name='Nome da Auditoria')),
                ('etapas', models.TextField(verbose_name='Etapas da Auditoria')),
                ('informacoes_campos_texto', models.TextField(verbose_name='Informações dos Campos de Texto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuarios_envolvidos', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuários Envolvidos')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_execucao', models.DateField(verbose_name='Data de Execução')),
                ('numero_acao', models.IntegerField(blank=True, null=True, verbose_name='Número da Ação')),
                ('avaliacao', models.TextField()),
                ('conclusao', models.TextField()),
                ('tipo_acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.tipoacao', verbose_name='Tipo de Ação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano')),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tipo_indice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.tipoindice', verbose_name='Tipo de Índice')),
            ],
            options={
                'unique_together': {('tipo_indice', 'mes', 'ano')},
            },
        ),
    ]
