# Generated by Django 5.2.8 on 2025-11-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
