# Generated by Django 5.2.8 on 2025-11-05 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='usuario',
            field=models.ForeignKey(
                default=1,  # Define um valor padrão para registros existentes
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário Responsável'
            ),
        ),
    ]
