# Generated by Django 5.2 on 2026-04-21 14:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Índice', 'verbose_name_plural': 'Índices'},
        ),
        migrations.AlterModelOptions(
            name='logacesso',
            options={'ordering': ['-data_hora_acesso'], 'verbose_name': 'Log de Acesso', 'verbose_name_plural': 'Logs de Acesso'},
        ),
        migrations.AlterModelOptions(
            name='tipoacao',
            options={'ordering': ['nome_acao'], 'verbose_name': 'Tipo de Ação', 'verbose_name_plural': 'Tipos de Ação'},
        ),
        migrations.AlterModelOptions(
            name='tipoindice',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Índice', 'verbose_name_plural': 'Tipos de Índice'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='id_unico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='indice',
            name='valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor (%)'),
        ),
        migrations.AddField(
            model_name='logacesso',
            name='id_unico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='indice',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='indice',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='logacesso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='tipoindice',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterUniqueTogether(
            name='tipoindice',
            unique_together={('descricao', 'indice_grupo')},
        ),
    ]
