# Generated by Django 5.2.8 on 2025-11-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_indice_valor'),
        ('Auth', '0002_auto_20251105_1944'),
    ]

    operations = [
    ]
