# Generated by Django 5.2 on 2026-04-21 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_indice_options_alter_logacesso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('base_legal', models.TextField(verbose_name='Base Legal')),
                ('riscos', models.TextField(verbose_name='Riscos Identificados')),
                ('procedimentos', models.TextField(verbose_name='Procedimentos de Auditoria')),
                ('conclusoes', models.TextField(blank=True, null=True, verbose_name='Conclusões')),
            ],
            options={
                'verbose_name': 'Matriz de Auditoria',
                'verbose_name_plural': 'Matrizes de Auditoria',
            },
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Auditoria', 'verbose_name_plural': 'Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': 'Configurações do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='historicoalteracoes',
            options={'ordering': ['-data_hora_alteracao'], 'verbose_name': 'Histórico de Alteração', 'verbose_name_plural': 'Histórico de Alterações'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-data_geracao'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='apuracao_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Apuração Final (R$)'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='apuracao_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Apuração Inicial (R$)'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Auth.matrizauditoria', verbose_name='Matriz de Auditoria'),
        ),
    ]
