# Generated by Django 5.2.8 on 2025-11-11 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_merge_0002_alter_indice_valor_0002_auto_20251105_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
