# Generated by Django 5.2 on 2026-04-21 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_matrizauditoria_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Entidade')),
            ],
            options={
                'verbose_name': 'Entidade de Auditoria',
                'verbose_name_plural': 'Entidades de Auditoria',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='matrizauditoria',
            options={'ordering': ['descricao'], 'verbose_name': 'Matriz de Auditoria', 'verbose_name_plural': 'Matrizes de Auditoria'},
        ),
        migrations.RemoveField(
            model_name='matrizauditoria',
            name='conclusoes',
        ),
        migrations.AddField(
            model_name='matrizauditoria',
            name='conclusoes_esperadas',
            field=models.CharField(default='', max_length=500, verbose_name='Conclusões da matriz de auditoria'),
        ),
        migrations.AddField(
            model_name='matrizauditoria',
            name='criterios_indicadores',
            field=models.CharField(default='', max_length=500, verbose_name='Critérios Indicadores da matriz de auditoria'),
        ),
        migrations.AddField(
            model_name='matrizauditoria',
            name='descricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição/Nome da matriz de auditoria'),
        ),
        migrations.AddField(
            model_name='matrizauditoria',
            name='objetivo',
            field=models.TextField(default='', verbose_name='Objetivo da matriz de auditoria'),
        ),
        migrations.AddField(
            model_name='matrizauditoria',
            name='observacoes',
            field=models.TextField(default='', verbose_name='Observações adicionais da matriz de auditoria'),
        ),
        migrations.AlterField(
            model_name='matrizauditoria',
            name='base_legal',
            field=models.CharField(default='', max_length=500, verbose_name='Base da matriz de auditoria'),
        ),
        migrations.AlterField(
            model_name='matrizauditoria',
            name='procedimentos',
            field=models.CharField(default='', max_length=500, verbose_name='Procedimentos da matriz de auditoria'),
        ),
        migrations.AlterField(
            model_name='matrizauditoria',
            name='riscos',
            field=models.CharField(default='', max_length=500, verbose_name='Riscos da matriz de auditoria'),
        ),
        migrations.AddField(
            model_name='matrizauditoria',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Auth.entidadeauditoria', verbose_name='Entidade da matriz de auditoria'),
        ),
    ]
