# Generated by Django 5.2 on 2026-04-20 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_acao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2031)], verbose_name='Ano'),
        ),
    ]
