# Generated by Django 5.2 on 2026-04-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_entidadeauditoria_alter_matrizauditoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoalteracoes',
            name='descricao_alteracao',
        ),
        migrations.RemoveField(
            model_name='historicoalteracoes',
            name='id_objeto',
        ),
        migrations.AddField(
            model_name='historicoalteracoes',
            name='estado_anterior',
            field=models.JSONField(blank=True, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AddField(
            model_name='historicoalteracoes',
            name='estado_posterior',
            field=models.JSONField(blank=True, null=True, verbose_name='Estado Posterior'),
        ),
        migrations.AddField(
            model_name='historicoalteracoes',
            name='operacao',
            field=models.CharField(choices=[('CRIADO', 'Criado'), ('ATUALIZADO', 'Atualizado'), ('EXCLUIDO', 'Excluído')], default='ATUALIZADO', max_length=10, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='historicoalteracoes',
            name='uuid_objeto',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID do Objeto'),
        ),
    ]
