# Generated by Django 5.2 on 2026-04-22 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_historicoalteracoes_descricao_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='etapas',
            field=models.TextField(blank=True, default='', verbose_name='Etapas da Auditoria'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='informacoes_campos_texto',
            field=models.TextField(blank=True, default='', verbose_name='Informações dos Campos de Texto'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuarios_envolvidos',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários Envolvidos'),
        ),
    ]
