# Generated by Django 5.2 on 2026-04-22 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_auditoria_etapas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='etapas',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='orgao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='responsavel_orgao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável do Órgão'),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('orientacao', models.TextField(verbose_name='Orientação')),
                ('documentos', models.TextField(blank=True, default='', verbose_name='Documentos')),
                ('atividade', models.CharField(max_length=500, verbose_name='Atividade')),
                ('prazo', models.DateField(verbose_name='Prazo')),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('REABERTA', 'Reaberta')], default='PENDENTE', max_length=20, verbose_name='Situação')),
                ('metodo', models.CharField(blank=True, default='', max_length=255, verbose_name='Método')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_list', to='Auth.auditoria', verbose_name='Auditoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['prazo'],
            },
        ),
        migrations.CreateModel(
            name='Achado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Achado')),
                ('data_achado', models.DateField(auto_now_add=True, verbose_name='Data do Achado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados', to='Auth.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Achado',
                'verbose_name_plural': 'Achados',
                'ordering': ['-data_achado'],
            },
        ),
    ]
