# Generated by Django 5.2 on 2026-05-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_indice_valor'),
        ('Auth', '0002_auto_20251105_1944'),
        ('Auth', '0007_remove_auditoria_etapas_auditoria_orgao_and_more'),
    ]

    operations = [
    ]
