# Generated by Django 5.2 on 2026-05-04 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_merge_20260504_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='is_paint',
            field=models.BooleanField(default=False, verbose_name='PAINT'),
        ),
        migrations.AddField(
            model_name='acao',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_REVISAO', 'Aguardando revisão'), ('HOMOLOGADA', 'Homologada'), ('ATRASADA', 'Atrasada')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='acao',
            name='unidade',
            field=models.CharField(choices=[('SEFAZ', 'SEFAZ'), ('SESAU', 'SESAU'), ('SEINFRA', 'SEINFRA'), ('SEMA', 'SEMA'), ('SEAD', 'SEAD'), ('SEDUC', 'SEDUC'), ('SESP', 'SESP'), ('SEAG', 'SEAG'), ('SEJEL', 'SEJEL'), ('SEDU', 'SEDU'), ('OUTRO', 'Outro')], default='SEFAZ', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='indice',
            name='valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor (%)'),
        ),
        migrations.AlterField(
            model_name='matrizauditoria',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações adicionais da matriz de auditoria'),
        ),
    ]
