# Generated by Django 5.2 on 2026-05-08 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_remove_perfil_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='Auth.perfil', verbose_name='Perfil Pai'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Auth.perfil', verbose_name='Perfil'),
        ),
    ]
