# Generated by Django 5.2 on 2026-07-04 17:27

from django.db import migrations, models


def backfill_id_por_orgao(apps, schema_editor):
    Auditoria = apps.get_model('Auth', 'Auditoria')
    contadores = {}
    for auditoria in Auditoria.objects.order_by('data_criacao'):
        contadores[auditoria.orgao] = contadores.get(auditoria.orgao, 0) + 1
        auditoria.id_por_orgao = contadores[auditoria.orgao]
        auditoria.save(update_fields=['id_por_orgao'])


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_encrypt_address_phone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='id_por_orgao',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Ref. Órgão'),
        ),
        migrations.RunPython(backfill_id_por_orgao, migrations.RunPython.noop),
    ]
