# Generated by Django 5.2 on 2026-07-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_auditoria_identificador_semantico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='unidade',
            field=models.CharField(blank=True, choices=[('SEFAZ', 'SEFAZ'), ('SESAU', 'SESAU'), ('SEINFRA', 'SEINFRA'), ('SEMA', 'SEMA'), ('SEAD', 'SEAD'), ('SEDUC', 'SEDUC'), ('SESP', 'SESP'), ('SEAG', 'SEAG'), ('SEJEL', 'SEJEL'), ('SEDU', 'SEDU'), ('OUTRO', 'Outro')], help_text='Se definida, restringe o acesso às Ações desta unidade. Deixe em branco para acesso irrestrito (ex.: controladoria).', max_length=20, null=True, verbose_name='Unidade'),
        ),
    ]
