# Generated by Django 5.2 on 2026-07-07 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_encrypt_achado_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='origem_mobile_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID de Origem (Mobile)'),
        ),
        migrations.CreateModel(
            name='ConflitoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dados_originador', models.JSONField(verbose_name='Dados do Originador')),
                ('dados_atuais', models.JSONField(verbose_name='Dados Atuais no Momento do Conflito')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido Em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atribuido_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflitos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído A')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflitos', to='Auth.etapa', verbose_name='Etapa')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflitos_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido Por')),
                ('usuario_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflitos_como_atual', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Versão Atual')),
                ('usuario_originador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflitos_originados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Originador')),
            ],
            options={
                'verbose_name': 'Conflito de Etapa',
                'verbose_name_plural': 'Conflitos de Etapa',
                'ordering': ['-criado_em'],
            },
        ),
    ]
